"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = []

AUTH_USER_MODEL = "accounts.CustomUser"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Added for allauth email verification
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    "corsheaders",
    'django_filters',
    'drf_spectacular',
    'django_q',
    'silk',
    'storages',
    "generic_notifications",

    # Allauth apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Social providers
    'allauth.socialaccount.providers.auth0',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.google',
    'dj_rest_auth',
    "dj_rest_auth.registration",

    # Local apps
    'auth.apps.AccountsConfig',
    'app_notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # account middleware:
    "allauth.account.middleware.AccountMiddleware",
    # Silk
    'silk.middleware.SilkyMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
#
                # `allauth` needs this from django
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',   # for anonymous users
        'rest_framework.throttling.UserRateThrottle',   # for authenticated users
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/minute',  # 10 requests per minute for anonymous users
        'user': '1000/hour',   # 100 requests per hour for logged-in users
    }
}

ACCOUNT_USER_MODEL_USERNAME_FIELD = None        # Disable username field completely
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*", "first_name", "last_name"]                   # Email is required
ACCOUNT_LOGIN_METHODS = {"email"}         # Login with email only
ACCOUNT_UNIQUE_EMAIL = True                  # Prevent duplicate emails
ACCOUNT_EMAIL_VERIFICATION = "mandatory"        # Require email verification
ACCOUNT_CONFIRM_EMAIL_ON_GET = True             # Allow email confirmation via GET request

# Email Configuration
# Use console backend for development, SMTP for production
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP Configuration (for production)
# Gmail SMTP settings (default)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_ID', default='')
EMAIL_HOST_PASSWORD = config('APP_PASSWORD', default='')

# Alternative SMTP providers (uncomment and configure as needed):
# Outlook/Hotmail: EMAIL_HOST = 'smtp-mail.outlook.com', EMAIL_PORT = 587
# Yahoo: EMAIL_HOST = 'smtp.mail.yahoo.com', EMAIL_PORT = 587
# SendGrid: EMAIL_HOST = 'smtp.sendgrid.net', EMAIL_PORT = 587
# Mailgun: EMAIL_HOST = 'smtp.mailgun.org', EMAIL_PORT = 587

# Email addresses
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@yourdomain.com')
SERVER_EMAIL = config('SERVER_EMAIL', default='server@yourdomain.com')

# Email timeout and connection settings
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=60, cast=int)
EMAIL_CONNECTION_TIMEOUT = config('EMAIL_CONNECTION_TIMEOUT', default=60, cast=int)

# SSL Configuration for email (fixes certificate verification issues)
import ssl
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = None
# Create SSL context that doesn't verify certificates (for development only)
if DEBUG:
    import ssl
    EMAIL_SSL_CONTEXT = ssl.create_default_context()
    EMAIL_SSL_CONTEXT.check_hostname = False
    EMAIL_SSL_CONTEXT.verify_mode = ssl.CERT_NONE
else:
    # For production, use proper SSL verification
    EMAIL_SSL_CONTEXT = None

# dj-rest-auth settings
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': 'jwt-auth',
    'JWT_AUTH_REFRESH_COOKIE': 'jwt-refresh',
    'JWT_AUTH_HTTPONLY': False,
    'SESSION_LOGIN': False,
    'REGISTER_SERIALIZER': 'auth.serializers.CustomRegisterSerializer',
    'LOGIN_ON_EMAIL_CONFIRMATION': False,  # Don't auto-login after email confirmation
    'LOGIN_ON_PASSWORD_RESET': False,      # Don't auto-login after password reset
}

# Override dj-rest-auth to use email instead of username
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'auth.serializers.CustomRegisterSerializer',
}

# Additional allauth settings for dj-rest-auth compatibility
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_EMAIL_CONFIRMATION_HMAC = True

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        # For each OAuth based provider, either add a ``SocialApp``
        # (``socialaccount`` app) containing the required client
        # credentials, or list them here:
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID'),
            'secret': config('GOOGLE_CLIENT_SECRET'),
        }
    }
}

# CORS SETTINGS

CORS_ALLOWED_ORIGINS=["http://localhost:5173"]

CORS_ALLOW_METHODS = (
    "DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT",
)

CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
)


# DRF-SPECTACULAR SETTINGS
SPECTACULAR_SETTINGS = {
    'TITLE': 'Your Project API',
    'DESCRIPTION': 'Your project description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

Q_CLUSTER = {
    'name': 'myproject',
    'workers': 8,
    'recycle': 500,
    'timeout': 60,
    'compress': True,
    'cpu_affinity': 1,
    'save_limit': 250,
    'queue_limit': 500,
    'label': 'Django Q',
    'redis': {
        'host': '127.0.0.1',
        'port': 6379,
        'db': 0,
    }
}


# Cloudflare R2 Configuration
CLOUDFLARE_R2_ACCESS_KEY_ID = config('CLOUDFLARE_R2_ACCESS_KEY_ID', default='your-access-key')
CLOUDFLARE_R2_SECRET_ACCESS_KEY = config('CLOUDFLARE_R2_SECRET_ACCESS_KEY', default='your-secret-key')
CLOUDFLARE_R2_BUCKET_NAME = config('CLOUDFLARE_R2_BUCKET_NAME', default='your-bucket-name')
CLOUDFLARE_R2_ENDPOINT_URL = config('CLOUDFLARE_R2_ENDPOINT_URL', default='https://your-account-id.r2.cloudflarestorage.com')
CLOUDFLARE_R2_CUSTOM_DOMAIN = config('CLOUDFLARE_R2_CUSTOM_DOMAIN', default=f'{CLOUDFLARE_R2_BUCKET_NAME}.your-account-id.r2.cloudflarestorage.com')

# Storage Configuration
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": CLOUDFLARE_R2_ACCESS_KEY_ID,
            "secret_key": CLOUDFLARE_R2_SECRET_ACCESS_KEY,
            "bucket_name": CLOUDFLARE_R2_BUCKET_NAME,
            "endpoint_url": CLOUDFLARE_R2_ENDPOINT_URL,
            "region_name": "auto",  # Cloudflare R2 uses "auto" as region
            "location": "media",
            "object_parameters": {
                "CacheControl": "max-age=86400",
            },
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3.S3StaticStorage",
        "OPTIONS": {
            "access_key": CLOUDFLARE_R2_ACCESS_KEY_ID,
            "secret_key": CLOUDFLARE_R2_SECRET_ACCESS_KEY,
            "bucket_name": CLOUDFLARE_R2_BUCKET_NAME,
            "endpoint_url": CLOUDFLARE_R2_ENDPOINT_URL,
            "region_name": "auto",  # Cloudflare R2 uses "auto" as region
            "location": "static",
            "object_parameters": {
                "CacheControl": "max-age=31536000",  # 1 year cache for static files
            },
        },
    },
}

# Static files configuration
STATIC_URL = f'https://{CLOUDFLARE_R2_CUSTOM_DOMAIN}/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files configuration
MEDIA_URL = f'https://{CLOUDFLARE_R2_CUSTOM_DOMAIN}/media/'

SITE_ID = 1



